version: 2.0
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:9.5.0
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Generate Site
          command: |
            CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN yarn generate

  deploy:
    working_directory: ~/workspace
    branches:
      only: 
        - master
        - contentful
    docker:
      - image: circleci/node:9.5.0
    steps:
      - run: 
          name: Deploy to GitHub
          command: |
            mkdir ~/.ssh
            echo "github.com ssh-rsa $GITHUB_DEPLOY_KNOWN_HOST" >> ~/.ssh/known_hosts
            git config user.email "bay.phillips@gmail.com"
            git config user.name "Bay Phillips"
            git add . 
            git commit -am "automated deploy [ci skip]"
            git push origin master
            