version: 2.0
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:9.5.0
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install Dependencies
          command: |
            yarn install
            pip install awscli --upgrade --user
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Generate Site
          command: CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - ./
      - run:
          name: Optionally deploy
          command: |
            if [ $CIRCLE_BRANCH == 'contentful' ]
            then
              yarn deploy
            fi

  deploy:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:9.5.0
      - image: circleci/python:3.6.1
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Install Dependencies
          command: pip install awscli --upgrade --user
      - run: 
          name: Deploy to S3
          command: yarn deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
