version: 2.0
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:9.5.0
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Generate Site
          command: CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - public
      - run:
          name: Optionally deploy
          command: |
            if [ $CIRCLE_BRANCH == 'contentful' ]
            then
              git config user.email "bay.phillips@gmail.com"
              git config user.name "Bay Phillips"
              git checkout . && git checkout master
              git commit --allow-empty -m "Content updated on Contentful"
              git push origin master
            fi

  deploy:
    working_directory: ~/workspace
    docker:
      - image: wilson208/circleci-awscli
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: 
          name: Deploy to S3
          command: aws s3 sync public s3://www.bayphillips.com --acl public-read --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
