version: 2.0

jobs:
  defaults: &defaults
    working_directory: ~/workspace
    docker:
      - image: circleci/node:9.5.0

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: 
        name: Install Dependencies
        command: yarn install
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
        name: Generate
        command: yarn generate
      # - persist_to_workspace:
      #   root: build
      #   paths:
      #     - ./*

  deploy:
    <<: *defaults
    steps:
      # - attach_workspace:
      #   at: ~/workspace/build
      - run: 
        name: Deploy to GitHub
        command: |
          git config user.email "bay.phillips@gmail.com"
          git config user.name "Bay Phillips"
          git add . 
          git commit -am "automated deploy [ci skip]"
          git push origin master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master


