# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.5.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: 
        name: Install Dependencies
        command: yarn install
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
        name: Generate
        command: yarn generate
      - persist_to_workspace:
        root: build

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
        at: ~/repo/build
      - run: 
        name: Deploy to GitHub
        command: |
          git config user.email "bay.phillips@gmail.com"
          git config user.name "Bay Phillips"
          git add . 
          git commit -am "automated deploy [ci skip]"
          git push origin master

workflows:
  version: 2
  build_only:
    jobs:
      - build
    filters:
      branches:
        ignore: /master/
  build_and_deploy:
    jobs:
      - build
      - deploy
    filters:
      branches:
        only: /master/


