version: 2.0
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:9.5.0
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "package-lock.json" }}
      - run: 
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}
      - run: 
          name: Generate Site
          command: |
            CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID \
            CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN \
            SITE_URL=$PRODUCTION_URL \
            S3_BUCKET=$S3_BUCKET \
            yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - public
            - .cache
            - node_modules
            - package.json
            - serverless.yml
            - lambdas
      - run:
          name: Optionally deploy
          command: |
            if [ $CIRCLE_BRANCH == 'contentful' ]
            then
              git config user.email "bay.phillips@gmail.com"
              git config user.name "Bay Phillips"
              git checkout . && git checkout master
              git pull
              git commit --allow-empty -m "Content updated on Contentful"
              git push origin master
            fi

  deploy:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:9.5.0
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: 
          name: Deploy Site to CloudFormation Stack
          no_output_timeout: 2h
          command: |
            yarn deploy --stage production --certificateArn $CLOUDFRONT_CERTIFICATE_ARN --s3Bucket $S3_BUCKET --domainName $S3_BUCKET --hostedZoneName $HOSTED_ZONE_NAME

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - master
                - s3originfix